site_name: HUF Core

theme:
  name: material

markdown_extensions:
  - attr_list
  - admonition
  - toc:
      permalink: true

nav:
  - Home: index.md
  - Start Here: start_here.md
  - Reference Manual: reference_manual.md
  - Handbook: handbook.md
  - Data Sources: data_sources.md
  - Troubleshooting: troubleshooting.md
  - GitHub for Beginners: github_for_beginners.md
  - GUI Quickstart: gui_quickstart.md
  - Theory Notes: theory_notes.md
  - Cases: cases.md
